import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1778153946533 implements MigrationInterface {
    name = 'Init1778153946533'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_verification_tokens_type_enum" AS ENUM('email_verification', 'password_reset')`);
        await queryRunner.query(`CREATE TABLE "user_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "token_hash" character varying NOT NULL, "type" "public"."user_verification_tokens_type_enum" NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "user_id" uuid, CONSTRAINT "PK_aec3eb060748f1cf7202e273bcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df64423cb719639b13f279fbd7" ON "user_verification_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE TYPE "public"."reservations_status_enum" AS ENUM('active', 'expired', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "reservations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "status" "public"."reservations_status_enum" NOT NULL DEFAULT 'active', "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "reservation_id" uuid NOT NULL, "ticket_type_id" uuid NOT NULL, "quantity" integer NOT NULL, CONSTRAINT "PK_bfc06fb7312bf99dd93bbe73844" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77fd31f8972b8cd9165c47443e" ON "reservation_items" ("reservation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0339f01f087da4672244ce7f4b" ON "reservation_items" ("ticket_type_id") `);
        await queryRunner.query(`CREATE TABLE "ticket_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL, "sold_quantity" integer NOT NULL DEFAULT '0', "reserved_quantity" integer NOT NULL DEFAULT '0', "sale_start" TIMESTAMP, "sale_end" TIMESTAMP, "event_id" uuid NOT NULL, CONSTRAINT "CHK_81c2c9ab96827387c2cb4d03ad" CHECK (sold_quantity + reserved_quantity <= quantity), CONSTRAINT "CHK_16f184e85147c73d0359213e28" CHECK (reserved_quantity >= 0), CONSTRAINT "CHK_2e476a06bc7aa455350a33304d" CHECK (sold_quantity >= 0), CONSTRAINT "CHK_d12a5037d650c4ff9bc8d50572" CHECK (quantity > 0), CONSTRAINT "PK_5510ce7e18a4edc648c9fbfc283" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50ec4cf7acfab01ce9c6cf9b48" ON "ticket_types" ("event_id", "sale_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3740a284eb6c6606b07d7c684" ON "ticket_types" ("event_id", "sale_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ca6c99484cff1ed8ed2aee725" ON "ticket_types" ("event_id", "price") `);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('draft', 'published', 'cancelled', 'finished')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying(150) NOT NULL, "description" text, "location" character varying(150) NOT NULL, "image_url" character varying, "image_public_id" character varying, "slug" character varying NOT NULL, "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP NOT NULL, "status" "public"."events_status_enum" NOT NULL DEFAULT 'draft', "published_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "organizer_id" uuid NOT NULL, "deleted_at" TIMESTAMP, CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bab6cf3a1e33e6790e9b9bd7d1" ON "events" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_df5d3d29b591928cede5717aba" ON "events" ("location") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_05bd884c03d3f424e2204bd14c" ON "events" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_03dcebc1ab44daa177ae9479c4" ON "events" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_22b517b56b453ab99a8fa1771d" ON "events" ("organizer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_000b23a3389237302df9250be5" ON "events" ("status", "start_date") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'ORGANIZER', 'event_staff', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."users_account_status_enum" AS ENUM('pending_verification', 'active', 'suspended', 'banned', 'deactivated')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "account_status" "public"."users_account_status_enum" NOT NULL DEFAULT 'pending_verification', "is_email_verified" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, "ticket_type_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_145532db85752b29c57d2b7b1f" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_41292b9bdd561fb442a064705d" ON "order_items" ("ticket_type_id") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'paid', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "total_amount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a922b820eeef29ac1c6800e826" ON "orders" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('valid', 'used', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, "ticket_type_id" uuid NOT NULL, "event_id" uuid NOT NULL, "code" character varying(64) NOT NULL, "qr_code_url" character varying(500), "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'valid', "used_at" TIMESTAMP, CONSTRAINT "UQ_c6e20a830c0f8b571abd331b775" UNIQUE ("code"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd5636236f799b19f132abf8d7" ON "tickets" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a95369aeea12da7fde110e95e0" ON "tickets" ("ticket_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd5387c23fb40ae7e3526ad75e" ON "tickets" ("event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'succeeded', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, "provider" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "provider_payment_id" character varying, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2f7b823a21562eeca20e72b00" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "event_staff_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "staff_id" uuid NOT NULL, "event_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "deactivated_at" TIMESTAMP, CONSTRAINT "UQ_098f41f7781710120d4d9090c86" UNIQUE ("staff_id", "event_id"), CONSTRAINT "PK_95d19d774f375424f6cc753a246" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43b699824526e0141952c154b7" ON "event_staff_assignments" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cefb8e8bc7e59bf4a67a37f365" ON "event_staff_assignments" ("event_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "token_hash" character varying NOT NULL, "ip_address" character varying NOT NULL, "user_agent" character varying NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "admin_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "admin_id" uuid NOT NULL, "action" character varying(100) NOT NULL, "resource" character varying(100) NOT NULL, "resource_id" uuid, "success" boolean NOT NULL DEFAULT true, "error_msg" text, "duration_ms" integer NOT NULL, CONSTRAINT "PK_de7a8fc2fbb525484c71a86bb96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01a78e07962ed72eaf9ccae990" ON "admin_audit_logs" ("admin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d588498ba31f5f480ff96df04a" ON "admin_audit_logs" ("resource_id") `);
        await queryRunner.query(`ALTER TABLE "user_verification_tokens" ADD CONSTRAINT "FK_0dbaa0aceff08b07a06e3a472d1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_4af5055a871c46d011345a255a6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation_items" ADD CONSTRAINT "FK_77fd31f8972b8cd9165c47443e7" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation_items" ADD CONSTRAINT "FK_0339f01f087da4672244ce7f4be" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_14c9ce53a2c2a1c781b8390123e" FOREIGN KEY ("organizer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_41292b9bdd561fb442a064705d7" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5636236f799b19f132abf8d70" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_a95369aeea12da7fde110e95e00" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_staff_assignments" ADD CONSTRAINT "FK_43b699824526e0141952c154b7c" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_staff_assignments" ADD CONSTRAINT "FK_cefb8e8bc7e59bf4a67a37f3658" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "event_staff_assignments" DROP CONSTRAINT "FK_cefb8e8bc7e59bf4a67a37f3658"`);
        await queryRunner.query(`ALTER TABLE "event_staff_assignments" DROP CONSTRAINT "FK_43b699824526e0141952c154b7c"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_a95369aeea12da7fde110e95e00"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5636236f799b19f132abf8d70"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_41292b9bdd561fb442a064705d7"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_14c9ce53a2c2a1c781b8390123e"`);
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20"`);
        await queryRunner.query(`ALTER TABLE "reservation_items" DROP CONSTRAINT "FK_0339f01f087da4672244ce7f4be"`);
        await queryRunner.query(`ALTER TABLE "reservation_items" DROP CONSTRAINT "FK_77fd31f8972b8cd9165c47443e7"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_4af5055a871c46d011345a255a6"`);
        await queryRunner.query(`ALTER TABLE "user_verification_tokens" DROP CONSTRAINT "FK_0dbaa0aceff08b07a06e3a472d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d588498ba31f5f480ff96df04a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01a78e07962ed72eaf9ccae990"`);
        await queryRunner.query(`DROP TABLE "admin_audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cefb8e8bc7e59bf4a67a37f365"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43b699824526e0141952c154b7"`);
        await queryRunner.query(`DROP TABLE "event_staff_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2f7b823a21562eeca20e72b00"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd5387c23fb40ae7e3526ad75e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a95369aeea12da7fde110e95e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd5636236f799b19f132abf8d7"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a922b820eeef29ac1c6800e826"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41292b9bdd561fb442a064705d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_account_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_000b23a3389237302df9250be5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22b517b56b453ab99a8fa1771d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03dcebc1ab44daa177ae9479c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05bd884c03d3f424e2204bd14c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df5d3d29b591928cede5717aba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bab6cf3a1e33e6790e9b9bd7d1"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ca6c99484cff1ed8ed2aee725"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3740a284eb6c6606b07d7c684"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50ec4cf7acfab01ce9c6cf9b48"`);
        await queryRunner.query(`DROP TABLE "ticket_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0339f01f087da4672244ce7f4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77fd31f8972b8cd9165c47443e"`);
        await queryRunner.query(`DROP TABLE "reservation_items"`);
        await queryRunner.query(`DROP TABLE "reservations"`);
        await queryRunner.query(`DROP TYPE "public"."reservations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df64423cb719639b13f279fbd7"`);
        await queryRunner.query(`DROP TABLE "user_verification_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."user_verification_tokens_type_enum"`);
    }

}
